### ISSUE TITLE
Bug: ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

### ISSUE THREAD

**Issue by tanlin2013** [primme/primme#59]
Hi there,

I'm switching the package manager from `pip` + `requirements.txt` to `poetry` for my project, and I found that this led to a `ValueError` when importing `primme`, while it was totally ok if I just install `primme` with `pip`. Though I'm not really certain this issue is not `poetry`-related. 

p.s. Both `pip` and `poetry` installation are tested within Docker, though I think this is not related...

Thanks!

Error Logs
-----
```
>>> import numpy as np
>>> import primme
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "primme.pyx", line 1, in init primme
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

Environment
------------
* Docker: `20.10.14, build a224086`
* Base Docker image: `python:3.10`
* Poetry: `1.2.0b1`
* numpy: `1.21.2`
* scipy: `1.8.0`
* primme: `3.2.1`

Dockerfile
-----------
```
FROM python:3.10

ARG WORKDIR=/home
ENV PYTHONPATH="${PYTHONPATH}:$WORKDIR" \
    PATH="/root/.local/bin:$PATH"
WORKDIR $WORKDIR
COPY . $WORKDIR

RUN apt update && \
    apt-get install -y --no-install-recommends \
      gfortran libblas-dev liblapack-dev

RUN curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.2.0b1 python3 - && \
    poetry config virtualenvs.create false --local && \
    poetry install
```

pyproject.toml
---------------
```
[tool.poetry]
name = "my_project"
version = "0.0.1"

[tool.poetry.dependencies]
python = "~3.10"
numpy = "1.21.2"
scipy = "1.8.0"
primme = "3.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

**Comment by tanlin2013** [comment]
**Note**: I have other packages that depends on `numba==0.55.1` (latest), which requires `numpy>=1.18,<1.22`. I have tried to upgrade `numpy` to `1.21.6`, but not helping.

**Comment by tanlin2013** [comment]
Hi again,

sorry, I think that's because I used the preview version of `poetry`, and so this issue probably has nothing to do with `primme`. I will transfer this issue to `poetry` team.
